name: Automatic Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

defaults:
  run:
    shell: powershell

jobs:
  update_choco:
    name: update_everything
    runs-on: windows-2022

    env:
      au_Push: "true"
      api_key: ${{ secrets.api_key }}
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git user
        run: |
          git config --global user.name "Chocolatey Automatic Updater"
          git config --global user.email "choco@someemail.com"

      - name: Install Chocolatey Automatic Package Updater Module
        shell: powershell
        run: |
          Install-Module -Name AU -Force -Scope CurrentUser -AllowClobber

      - name: Run update script
        shell: powershell
        run: |
          .\update_all.ps1

      - name: Save artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Results
          if-no-files-found: warn
          path: |
            Update-AUPackages.md
            Update-History.md
            update_info.xml
